// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAg1_Oiqit40M33ifuQDq8nC0ILA_K650',
    appId: '1:1056630753747:web:a7a7b5d2fd061d4ed84726',
    messagingSenderId: '1056630753747',
    projectId: 'pontosturisticoslitoralpi',
    authDomain: 'pontosturisticoslitoralpi.firebaseapp.com',
    storageBucket: 'pontosturisticoslitoralpi.firebasestorage.app',
    measurementId: 'G-8SF9RWP20D',
    databaseURL: 'https://pontosturisticoslitoralpi-default-rtdb.firebaseio.com'

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0fg_gCJDTEs1U3rcDg0fNqpvvcKBljYM',
    appId: '1:1056630753747:android:c15b9ced5b2249b1d84726',
    messagingSenderId: '1056630753747',
    projectId: 'pontosturisticoslitoralpi',
    storageBucket: 'pontosturisticoslitoralpi.firebasestorage.app',
    databaseURL: 'https://pontosturisticoslitoralpi-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDksSSGJF9cE3wzF1f1BiDSM-t3uLJvjmQ',
    appId: '1:1056630753747:ios:599514c8af65227bd84726',
    messagingSenderId: '1056630753747',
    projectId: 'pontosturisticoslitoralpi',
    storageBucket: 'pontosturisticoslitoralpi.firebasestorage.app',
    iosBundleId: 'com.example.litoralTuristico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDksSSGJF9cE3wzF1f1BiDSM-t3uLJvjmQ',
    appId: '1:1056630753747:ios:599514c8af65227bd84726',
    messagingSenderId: '1056630753747',
    projectId: 'pontosturisticoslitoralpi',
    storageBucket: 'pontosturisticoslitoralpi.firebasestorage.app',
    iosBundleId: 'com.example.litoralTuristico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAg1_Oiqit40M33ifuQDq8nC0ILA_K650',
    appId: '1:1056630753747:web:4614460bee69ae3dd84726',
    messagingSenderId: '1056630753747',
    projectId: 'pontosturisticoslitoralpi',
    authDomain: 'pontosturisticoslitoralpi.firebaseapp.com',
    storageBucket: 'pontosturisticoslitoralpi.firebasestorage.app',
    measurementId: 'G-RV8V54KBDW',
  );

}